"""
Group actions for the twin-spaces generator.

A *twin space* is produced from three primitives (Vol. 01, Twin Spaces):

1. a base space ``(E, ⊙_e)`` — a set with a binary operation,
2. a group ``G`` acting on ``E``,
3. the transport formula  ``x ⊙_{eg} y = g⁻¹·((g·x) ⊙_e (g·y))``.

This module supplies the second primitive in three flavours, covering the
families requested in the foundations volume:

* :class:`BijectionAction` — a *monogenic* group ``G = ⟨φ⟩ ≅ ℤ`` generated by
  a bijection ``φ`` acting by iterated composition ``φ^{(n)}`` (the exponential
  hierarchy and its generalisations).
* :class:`ContinuousAction` — a *one-parameter Lie group* (e.g. ``(ℝ,+)`` or
  ``(ℝ_{>0},×)``) acting by a closed-form family ``t·x``.
* :class:`PermutationAction` — a *finite group* given concretely as a set of
  permutations of a finite set ``E = {0,…,m-1}`` (cyclic, symmetric, dihedral,
  Klein, …), with full group arithmetic.

Each action exposes the two operations the transport formula needs: ``act`` for
``g·x`` and an inverse (``inverse_level`` / ``inv_param`` / ``inverse``).
"""

from itertools import permutations
from typing import Callable, List, Sequence, Tuple

import sympy as sp
from sympy import exp, log, sympify, Symbol

from arithmetics.symbolic.expressions import x as _x  # shared positive symbol


__all__ = ["BijectionAction", "ContinuousAction", "PermutationAction"]


# ---------------------------------------------------------------------------
# Monogenic group generated by a bijection  (G = ⟨φ⟩ ≅ ℤ)
# ---------------------------------------------------------------------------
class BijectionAction:
    """A monogenic action ``G = ⟨φ⟩`` acting on ``E`` by ``n·x = φ^{(n)}(x)``.

    ``φ`` and ``φ⁻¹`` are callables on SymPy expressions; the group element is
    the integer ``n`` (iteration count), with inverse ``-n``.
    """

    kind = "monogenic"

    def __init__(self, name: str, phi: Callable, phi_inverse: Callable,
                 domain: str = "ℝ"):
        self.name = name
        self._phi = phi
        self._phi_inv = phi_inverse
        self.domain = domain

    def act(self, level: int, value) -> sp.Expr:
        """Apply ``φ^{(level)}`` to ``value`` (negative ⇒ iterate ``φ⁻¹``)."""
        value = sympify(value)
        level = int(level)
        f = self._phi if level >= 0 else self._phi_inv
        for _ in range(abs(level)):
            value = f(value)
        return value

    def inverse_level(self, level: int) -> int:
        return -int(level)

    # -- catalogue of canonical bijections ---------------------------------
    @classmethod
    def identity(cls) -> "BijectionAction":
        return cls("id", lambda v: v, lambda v: v, domain="ℝ")

    @classmethod
    def exponential(cls) -> "BijectionAction":
        return cls("exp", lambda v: exp(v), lambda v: log(v), domain="ℝ_{>0}")

    @classmethod
    def power(cls, p) -> "BijectionAction":
        p = sympify(p)
        return cls(f"x^{p}", lambda v: v ** p, lambda v: v ** (1 / p),
                   domain="ℝ_{>0}")

    @classmethod
    def affine(cls, a, b) -> "BijectionAction":
        a, b = sympify(a), sympify(b)
        return cls(f"{a}x+{b}", lambda v: a * v + b, lambda v: (v - b) / a,
                   domain="ℝ")

    @classmethod
    def logit(cls) -> "BijectionAction":
        return cls("logit",
                   lambda v: log(v / (1 - v)),
                   lambda v: 1 / (1 + exp(-v)),
                   domain="(0,1)")

    def __repr__(self) -> str:
        return f"BijectionAction({self.name!r})"


# ---------------------------------------------------------------------------
# One-parameter Lie group  (continuous deformation parameter)
# ---------------------------------------------------------------------------
class ContinuousAction:
    """A one-parameter group action with a *continuous* parameter ``t``.

    ``act(t, x)`` is the closed-form action ``t·x``; ``inv_param(t)`` gives the
    group inverse of the parameter (``-t`` for ``(ℝ,+)``, ``1/t`` for
    ``(ℝ_{>0},×)``). The transport then produces a twin operation depending
    symbolically on ``t``.
    """

    kind = "lie"

    def __init__(self, name: str, group: str, act: Callable,
                 inv_param: Callable, param: Symbol):
        self.name = name
        self.group = group
        self._act = act
        self._inv_param = inv_param
        self.param = param

    def act(self, t, value) -> sp.Expr:
        return self._act(sympify(t), sympify(value))

    def inv_param(self, t):
        return self._inv_param(sympify(t))

    # -- catalogue of canonical Lie actions --------------------------------
    @classmethod
    def scaling(cls, t: Symbol = None) -> "ContinuousAction":
        """``G = (ℝ,+)`` acting on ``ℝ_{>0}`` by ``t·x = e^t x``."""
        t = t or Symbol("t", real=True)
        return cls("scaling", "(ℝ,+)",
                   lambda tt, v: exp(tt) * v, lambda tt: -tt, t)

    @classmethod
    def translation(cls, t: Symbol = None) -> "ContinuousAction":
        """``G = (ℝ,+)`` acting on ``ℝ`` by ``t·x = x + t``."""
        t = t or Symbol("t", real=True)
        return cls("translation", "(ℝ,+)",
                   lambda tt, v: v + tt, lambda tt: -tt, t)

    @classmethod
    def power(cls, a: Symbol = None) -> "ContinuousAction":
        """``G = (ℝ_{>0},×)`` acting on ``ℝ_{>0}`` by ``a·x = x^a``."""
        a = a or Symbol("a", positive=True)
        return cls("power", "(ℝ_{>0},×)",
                   lambda aa, v: v ** aa, lambda aa: 1 / aa, a)

    def __repr__(self) -> str:
        return f"ContinuousAction({self.name!r}, G={self.group})"


# ---------------------------------------------------------------------------
# Finite group of permutations of E = {0, …, m-1}
# ---------------------------------------------------------------------------
class PermutationAction:
    """A finite group acting on ``E = {0,…,size-1}`` by permutations.

    Group elements are stored as tuples ``p`` with ``p[i] = g·i``. Provides the
    group arithmetic (identity, inverse, composition, powers) needed for
    transport, the structural kernel, and complexity.
    """

    kind = "finite"

    def __init__(self, name: str, size: int, elements: Sequence[Sequence[int]]):
        self.name = name
        self.size = size
        # de-duplicate while keeping a deterministic order
        self.elements: List[Tuple[int, ...]] = sorted({tuple(p) for p in elements})

    # -- group arithmetic --------------------------------------------------
    def identity(self) -> Tuple[int, ...]:
        return tuple(range(self.size))

    def inverse(self, p: Sequence[int]) -> Tuple[int, ...]:
        inv = [0] * self.size
        for i, pi in enumerate(p):
            inv[pi] = i
        return tuple(inv)

    def compose(self, p: Sequence[int], q: Sequence[int]) -> Tuple[int, ...]:
        """Return ``p ∘ q`` (apply ``q`` then ``p``)."""
        return tuple(p[q[i]] for i in range(self.size))

    def power(self, p: Sequence[int], k: int) -> Tuple[int, ...]:
        r = self.identity()
        for _ in range(k):
            r = self.compose(p, r)
        return r

    def act(self, p: Sequence[int], i: int) -> int:
        return p[i]

    @property
    def order(self) -> int:
        return len(self.elements)

    # -- catalogue of canonical finite groups ------------------------------
    @classmethod
    def trivial(cls, size: int) -> "PermutationAction":
        return cls(f"1 (m={size})", size, [tuple(range(size))])

    @classmethod
    def cyclic(cls, n: int) -> "PermutationAction":
        """``C_n`` acting on ``{0,…,n-1}`` by the n-cycle ``(0 1 … n-1)``."""
        gen = tuple((i + 1) % n for i in range(n))
        return cls.generated_by(f"C_{n}", n, [gen])

    @classmethod
    def symmetric(cls, n: int) -> "PermutationAction":
        """``S_n`` acting on ``{0,…,n-1}`` (all permutations)."""
        return cls(f"S_{n}", n, list(permutations(range(n))))

    @classmethod
    def dihedral(cls, n: int) -> "PermutationAction":
        """``D_n`` (order ``2n``) acting on the vertices of an ``n``-gon."""
        rot = tuple((i + 1) % n for i in range(n))
        ref = tuple((-i) % n for i in range(n))
        return cls.generated_by(f"D_{n}", n, [rot, ref])

    @classmethod
    def klein_four(cls) -> "PermutationAction":
        """The Klein four-group acting on ``{0,1,2,3}``."""
        return cls("V_4", 4, [
            (0, 1, 2, 3),
            (1, 0, 3, 2),
            (2, 3, 0, 1),
            (3, 2, 1, 0),
        ])

    @classmethod
    def generated_by(cls, name: str, size: int,
                     generators: Sequence[Sequence[int]]) -> "PermutationAction":
        """Close a set of generating permutations into a full group."""
        idt = tuple(range(size))
        gens = [tuple(g) for g in generators]

        def comp(p, q):
            return tuple(p[q[i]] for i in range(size))

        seen = {idt, *gens}
        queue = list(seen)
        while queue:
            a = queue.pop()
            for g in gens:
                for prod in (comp(a, g), comp(g, a)):
                    if prod not in seen:
                        seen.add(prod)
                        queue.append(prod)
        return cls(name, size, seen)

    def __repr__(self) -> str:
        return f"PermutationAction({self.name!r}, |G|={self.order}, m={self.size})"
