/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheorieRouteImport } from './routes/theorie'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RessourcesIndexRouteImport } from './routes/ressources/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RessourcesSlugRouteImport } from './routes/ressources/$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const TheorieRoute = TheorieRouteImport.update({
  id: '/theorie',
  path: '/theorie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesIndexRoute = RessourcesIndexRouteImport.update({
  id: '/ressources/',
  path: '/ressources/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesSlugRoute = RessourcesSlugRouteImport.update({
  id: '/ressources/$slug',
  path: '/ressources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/theorie': typeof TheorieRoute
  '/admin/login': typeof AdminLoginRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ressources/': typeof RessourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/theorie': typeof TheorieRoute
  '/admin/login': typeof AdminLoginRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/ressources': typeof RessourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/theorie': typeof TheorieRoute
  '/admin/login': typeof AdminLoginRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ressources/': typeof RessourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/theorie'
    | '/admin/login'
    | '/ressources/$slug'
    | '/admin/'
    | '/ressources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/theorie'
    | '/admin/login'
    | '/ressources/$slug'
    | '/admin'
    | '/ressources'
  id:
    | '__root__'
    | '/'
    | '/theorie'
    | '/admin/login'
    | '/ressources/$slug'
    | '/admin/'
    | '/ressources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TheorieRoute: typeof TheorieRoute
  AdminLoginRoute: typeof AdminLoginRoute
  RessourcesSlugRoute: typeof RessourcesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RessourcesIndexRoute: typeof RessourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theorie': {
      id: '/theorie'
      path: '/theorie'
      fullPath: '/theorie'
      preLoaderRoute: typeof TheorieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/': {
      id: '/ressources/'
      path: '/ressources'
      fullPath: '/ressources/'
      preLoaderRoute: typeof RessourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/$slug': {
      id: '/ressources/$slug'
      path: '/ressources/$slug'
      fullPath: '/ressources/$slug'
      preLoaderRoute: typeof RessourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TheorieRoute: TheorieRoute,
  AdminLoginRoute: AdminLoginRoute,
  RessourcesSlugRoute: RessourcesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  RessourcesIndexRoute: RessourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
